language: go
go: 1.1
services: 
  - mongodb
install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v github.com/robfig/revel/revel
  - go get -v github.com/robfig/revel/harness
  - go get -v labix.org/v2/mgo
  - go get -v labix.org/v2/mgo/bson

script:
  - go test github.com/robfig/revel
  - go test github.com/robfig/revel/harness

  # Build & run the sample apps
  - revel test github.com/jgraham909/revmgo/testapp
